/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109562-g0431f9805e-20230110"
#endif /* AVUTIL_FFVERSION_H */
